[tool.poetry]
name = "pythonproject1"
version = "0.1.0"
description = ""
authors = ["apvap <apvapolorlorlsdold@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
pandas = "==2.3.0"
openpyxl = "==3.2.0b1"
python-dotenv = "^1.1.1"
pytest = "^8.4.1"
pytest-cov = "^6.2.1"
flake8 = "^7.3.0"
mypy = "^1.16.1"
isort = "^6.0.1"
pandas-stubs = "^2.3.0.250703"
black = "^25.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
